@url = http://localhost:5000/auth/


###
POST {{url}}login
Content-Type: application/json

{
    "username" : "calvarez",
    "password" : "123456789"    
}


###
POST {{url}}register
Content-Type: application/json

{
    "username" : "calvarez",
    "password" : "123456789"    
}

