export const ciQueries = {
  getAllChargeImport: `SELECT top 200 * 
                   FROM ChargeImport`,

  postNewChargeImport: `INSERT INTO ChargeImport 
                        (BillCoID,ClientID,SrcFileImportDate,SrcItemImportDateWTime,SourceName,SourceImportID,ChargeImportDate,ChargeImportUserID,LastUserID,LastUserUpdate,PatientFirstName,PatientMiddleName,PatientLastName,PatientStreet,PatientStreet2,PatientCity,PatientState,PatientZip,PatientDOB,PatientSex,PatientPhoneNumber,PatientSSN,PatientIDType,PatientDriversLicense,PatientConsent,PatientTRF_Form,SubscriberFirstName,SubscriberLastName,SubscriberDOB,PrimaryInsName,PrimaryInsPolicyNo,PrimaryInsGroupNo,PrimaryInsRelation,InsCardFront,InsCardBack,SecondaryInsName,SecondaryInsPolicyNo,SecondaryInsGroupNo,OrderingProviderNPI,OrderingProviderName,OrderingProviderStreet,OrderingProviderStreet2,OrderingProviderCity,OrderingProviderState,OrderingProviderZip,OrderingProviderPhone,OrderingProviderEmail,FacilityID,FacilityName,FacilityStreet,FacilityCity,FacilityState,FacilityZip,FacilityCLIA,AccessionNo,DateOfService,DateOfResults,CPTCode1,CPTCode2,CPTCode3,CPTCode4,CPTCode5,CPTCode6,ICD10Code1,ICD10Code2,ICD10Code3,ICD10Code4,ICD10Code5,ICD10Code6,ICD10Code7,ICD10Code8,ICD10Code9,ICD10Code10,ICD10Code11,ICD10Code12,ServiceType,ClientNotes,SubClientName,PartnerGroupName,Barcode,WSLOrderID,InsMissing,DateToProduction,ProcessStage,NeedsReview,IssueID,InNGO,NGO_IsBalance)
                        VALUES
                        (@BillCoID,@ClientID,@SrcFileImportDate,@SrcItemImportDateWTime,@SourceName,@SourceImportID,@ChargeImportDate,@ChargeImportUserID,@LastUserID,@LastUserUpdate,@PatientFirstName,@PatientMiddleName,@PatientLastName,@PatientStreet,@PatientStreet2,@PatientCity,@PatientState,@PatientZip,@PatientDOB,@PatientSex,@PatientPhoneNumber,@PatientSSN,@PatientIDType,@PatientDriversLicense,@PatientConsent,@PatientTRF_Form,@SubscriberFirstName,@SubscriberLastName,@SubscriberDOB,@PrimaryInsName,@PrimaryInsPolicyNo,@PrimaryInsGroupNo,@PrimaryInsRelation,@InsCardFront,@InsCardBack,@SecondaryInsName,@SecondaryInsPolicyNo,@SecondaryInsGroupNo,@OrderingProviderNPI,@OrderingProviderName,@OrderingProviderStreet,@OrderingProviderStreet2,@OrderingProviderCity,@OrderingProviderState,@OrderingProviderZip,@OrderingProviderPhone,@OrderingProviderEmail,@FacilityID,@FacilityName,@FacilityStreet,@FacilityCity,@FacilityState,@FacilityZip,@FacilityCLIA,@AccessionNo,@DateOfService,@DateOfResults,@CPTCode1,@CPTCode2,@CPTCode3,@CPTCode4,@CPTCode5,@CPTCode6,@ICD10Code1,@ICD10Code2,@ICD10Code3,@ICD10Code4,@ICD10Code5,@ICD10Code6,@ICD10Code7,@ICD10Code8,@ICD10Code9,@ICD10Code10,@ICD10Code11,@ICD10Code12,@ServiceType,@ClientNotes,@SubClientName,@PartnerGroupName,@Barcode,@WSLOrderID,@InsMissing,@DateToProduction,@ProcessStage,@NeedsReview,@IssueID,@InNGO,@NGO_IsBalance)`,

  getChargeImportById: `SELECT * FROM ChargeImport WHERE ChgImportID = @id`,

  deleteChargeImportById: `DELETE FROM ChargeImport WHERE ChgImportID = @id`,
  
  getTotalChargeImport: `SELECT COUNT(*) FROM ChargeImport`,

  putChargeImportById: `UPDATE ci 
                        SET BillCoID = @BillCoID, ClientID = @ClientID, SrcFileImportDate = @SrcFileImportDate, SrcItemImportDateWTime = @SrcItemImportDateWTime, SourceName = @SourceName, SourceImportID = @SourceImportID, ChargeImportDate = @ChargeImportDate, ChargeImportUserID = @ChargeImportUserID, LastUserID = @LastUserID, LastUserUpdate = @LastUserUpdate, PatientFirstName = @PatientFirstName, PatientMiddleName = @PatientMiddleName, PatientLastName = @PatientLastName, PatientStreet = @PatientStreet, PatientStreet2 = @PatientStreet2, PatientCity = @PatientCity, PatientState = @PatientState, PatientZip = @PatientZip, PatientDOB = @PatientDOB, PatientSex = @PatientSex, PatientPhoneNumber = @PatientPhoneNumber, PatientSSN = @PatientSSN, PatientIDType = @PatientIDType, PatientDriversLicense = @PatientDriversLicense, PatientConsent = @PatientConsent, PatientTRF_Form = @PatientTRF_Form, SubscriberFirstName = @SubscriberFirstName, SubscriberLastName = @SubscriberLastName, SubscriberDOB = @SubscriberDOB, PrimaryInsName = @PrimaryInsName, PrimaryInsPolicyNo = @PrimaryInsPolicyNo, PrimaryInsGroupNo = @PrimaryInsGroupNo, PrimaryInsRelation = @PrimaryInsRelation, InsCardFront = @InsCardFront, InsCardBack = @InsCardBack, SecondaryInsName = @SecondaryInsName, SecondaryInsPolicyNo = @SecondaryInsPolicyNo, SecondaryInsGroupNo = @SecondaryInsGroupNo, OrderingProviderNPI = @OrderingProviderNPI, OrderingProviderName = @OrderingProviderName, OrderingProviderStreet = @OrderingProviderStreet, OrderingProviderStreet2 = @OrderingProviderStreet2, OrderingProviderCity = @OrderingProviderCity, OrderingProviderState = @OrderingProviderState, OrderingProviderZip = @OrderingProviderZip, OrderingProviderPhone = @OrderingProviderPhone, OrderingProviderEmail = @OrderingProviderEmail, FacilityID = @FacilityID, FacilityName = @FacilityName, FacilityStreet = @FacilityStreet, FacilityCity = @FacilityCity, FacilityState = @FacilityState, FacilityZip = @FacilityZip, FacilityCLIA = @FacilityCLIA, AccessionNo = @AccessionNo, DateOfService = @DateOfService, DateOfResults = @DateOfResults, CPTCode1 = @CPTCode1, CPTCode2 = @CPTCode2, CPTCode3 = @CPTCode3, CPTCode4 = @CPTCode4, CPTCode5 = @CPTCode5, CPTCode6 = @CPTCode6, ICD10Code1 = @ICD10Code1, ICD10Code2 = @ICD10Code2, ICD10Code3 = @ICD10Code3, ICD10Code4 = @ICD10Code4, ICD10Code5 = @ICD10Code5, ICD10Code6 = @ICD10Code6, ICD10Code7 = @ICD10Code7, ICD10Code8 = @ICD10Code8, ICD10Code9 = @ICD10Code9, ICD10Code10 = @ICD10Code10, ICD10Code11 = @ICD10Code11, ICD10Code12 = @ICD10Code12, ServiceType = @ServiceType, ClientNotes = @ClientNotes, SubClientName = @SubClientName, PartnerGroupName = @PartnerGroupName, Barcode = @Barcode, WSLOrderID = @WSLOrderID, InsMissing = @InsMissing, DateToProduction = @DateToProduction, ProcessStage = @ProcessStage, NeedsReview = @NeedsReview, IssueID = @IssueID, InNGO = @InNGO, NGO_IsBalance = @NGO_IsBalance  
                        FROM ChargeImport ci
                        WHERE ChgImportID = @id`,
}
